### ISSUE TITLE
Can't add sound to pimatic rule

### ISSUE THREAD

**Issue by kjdijkema** [appzer/pimatic-pushsafer#3]
When I create a rule in pimatic, using the example line
` push title:"Good morning!" message:"Time to get out of bed!" sound:"11" device:"312" icon:"4" vibration:"2" url:"https://www.pushsafer.com" urltitle:"Open Pushsafer" time2live:"60"`, 
I receive this error:
` Expected: "and", got " device:"312" icon:"4" vibration:"2" url:"https://www.pushsafer.com" urltitle:"Open Pushsafer" time2live:"60` 
and I can't save the rule.
When I remove 
`sound:"11"`,
there is no error and I can save the rule.

**Comment by appzer** [comment]
Hi,

can not find any mistake. For me it works. Pleasse try this line

`push title:"Good morning!" message:"Time to get out of bed!" sound:11 device:312 icon:4 vibration:2 url:"https://www.pushsafer.com" urltitle:"Open Pushsafer" time2live:60`

Otherwise you can create an alias key with predefined icon and sound in your pushsafer dashboard.
Instead of your private key you have to use the alias key.

Hope this helps.

Kevin

**Comment by kjdijkema** [comment]
I tried that line, gives a similar error.
The thing is, Kevin, I paid for your services to receive notifications and I'm trying to be helpful by submitting this issue. Your reaction is to close the issue, no questions asked. Wow.
Thanks for suggesting the alias key though, guess I'll have to go for the work-around then.

**Comment by appzer** [comment]
Hi,

can you provide more error details!
